metasploit_meterpreter: |
    use post/multi/recon/local_exploit_suggester
    <ruby>
        sleep 2
        self.active_module.datastore["SESSION"] = framework.sessions.keys.max
        puts "Use session " + self.active_module.datastore["SESSION"].to_s
    </ruby>
    run
