reverse_shell_raw:
  payload: 
    name: reverse_shell_raw
    base64: false
    available_loaders:
      - wget_generic
      - wget_bash

reverse_shell_raw_base64:
  payload: 
    name: reverse_shell_raw
    base64: true
    available_loaders:
      - wget_generic_base64
      - wget_bash_base64
      - generic_inline_base64

reverse_shell_bash:
  payload: 
    name: reverse_shell_bash
    base64: false
    available_loaders:
      - wget_generic
      - wget_bash

reverse_shell_bash_base64:
  payload: 
    name: reverse_shell_bash
    base64: true
    available_loaders:
      - wget_generic_base64
      - wget_bash_base64
      - generic_inline_base64

reverse_shell_elf:
  payload: 
    name: reverse_shell_elf
    base64: false
    binary: true
    available_loaders:
      - wget_generic

reverse_shell_elf_base64:
  payload: 
    name: reverse_shell_elf
    base64: true
    available_loaders:
      - wget_generic_base64
      - generic_inline_base64

reverse_shell_elf_python:
  payload:
    name: reverse_shell_elf_python
    base64: false
    available_loaders:
      - python
      - python2

reverse_shell_elf_python_base64:
  payload:
    name: reverse_shell_elf_python
    base64: true
    available_loaders:
      - python_base64
      - python2_base64
      - python_inline_base64

meterpreter_base64:
  payload: 
    name: meterpreter
    base64: true
    available_loaders:
      - wget_generic_base64
      - generic_inline_base64
  exploits:
    - handlers.meterpreter
    - recon.metasploit_meterpreter
    - escalation.metasploit_meterpreter_bpf
    - misc.metasploit_meterpreter_getconfigs

meterpreter_shi:
  payload: 
    name: meterpreter_shi
    base64: false
    binary: true
    available_loaders:
      - wget_generic
  exploits:
    - handlers.meterpreter
    - recon.metasploit_meterpreter
    - escalation.metasploit_meterpreter_bpf
    - misc.metasploit_meterpreter_getconfigs

meterpreter_shi_base64:
  payload: 
    name: meterpreter_shi
    base64: true
    available_loaders:
      - wget_generic_base64
      - generic_inline_base64
  exploits:
    - handlers.meterpreter
    - recon.metasploit_meterpreter
    - escalation.metasploit_meterpreter_bpf
    - misc.metasploit_meterpreter_getconfigs

meterpreter_shi_iter:
  payload: 
    name: meterpreter_shi_iter
    base64: false
    binary: true
    available_loaders:
      - wget_generic
  exploits:
    - handlers.meterpreter
    - recon.metasploit_meterpreter
    - escalation.metasploit_meterpreter_bpf
    - misc.metasploit_meterpreter_getconfigs

meterpreter_shi_iter_base64:
  payload: 
    name: meterpreter_shi_iter
    base64: true
    available_loaders:
      - wget_generic_base64
      - generic_inline_base64
  exploits:
    - handlers.meterpreter
    - recon.metasploit_meterpreter
    - escalation.metasploit_meterpreter_bpf
    - misc.metasploit_meterpreter_getconfigs
